# Generated by Django 3.1.4 on 2021-01-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210108_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='uuid',
        ),
    ]
