# Generated by Django 3.1.4 on 2020-12-29 18:23

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201229_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.FileField(blank=True, default=None, upload_to=home.models.upload_location),
        ),
    ]
