# Generated by Django 3.1.4 on 2021-01-11 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_video_videodisplay'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_time']},
        ),
        migrations.AddField(
            model_name='video',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 11, 18, 9, 12, 726466)),
        ),
    ]
