# Generated by Django 3.1.4 on 2021-01-11 15:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210111_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 11, 21, 24, 43, 846003)),
        ),
        migrations.CreateModel(
            name='VideoSidebar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_sidebar', models.TextField(blank=True, default=None)),
                ('videos', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.video')),
            ],
        ),
    ]
