# Generated by Django 3.1.4 on 2021-01-08 14:37

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('content', models.TextField(default='')),
                ('subtitle', models.TextField(default='')),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField(default='')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
            options={
                'ordering': ['startdate'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, upload_to=events.models.upload_location)),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
