# Generated by Django 3.1.4 on 2021-01-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtable',
            name='description_for_day',
            field=models.TextField(default=''),
        ),
    ]
