# Generated by Django 3.1.4 on 2021-01-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventtable_description_for_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtable',
            name='title_for_day',
            field=models.CharField(default='', max_length=100),
        ),
    ]
